---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или
    категории
  - пользователь должен иметь возможность фильтровать товары
  - пользователь должен иметь возможность просматривать товары и просматривать
    подробную информацию о товаре
  - пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - возможность магазина - адаптивная верстка, чтобы он был удобным на мобильных устройствах
  - интерфейс магазина с просмотром, фильтрацией товаров и добавлением их в корзину
  - интернет - магазин — это SPA приложение, которое не перезагружает страницу
  - пользователь может просматривать каталог товаров, фильтруя их и пользуясь постраничным выводом
  - на странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без
  - пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге
  - на странице корзины пользователь может удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты
  - корзина хранится в сессии браузера
  - сайт должен быть доступен на различных устройствах 
non-functional:
  - веб-сайт должен быть разработан с учетом удобства использования и
    оптимизирован для скорости работы
  - сайт должен быть безопасным и защищать данные пользователя
  - сайт должен иметь мобильную версию
  - сайт должен быть протестирован на совместимость с последними версиями
    браузеров
  - сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - идентификация пользователя (вход/регистрация) 
  - локализация 
  - корректное отображение стоимости товаров со скидкой и без скидки на странице корзины  
  - поиск, фильтрация товаров осуществляется по всему ассортименту существующих на сайте товаров
